version: '3.6'

services:
  db:
    restart: unless-stopped
    image: postgres:15-alpine
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Stockholm
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  db-data:
